name: hanzo
version: "3"
services:
  nginx:
    image: "nginx:1.21.3"
    ports:
      - "0.0.0.0:81:80"
    volumes:
      - ./.hanzo.nginx:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - hanzo-network-platform

  mongodb:
    image: "mongo:7-jammy"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - db:/data/db
    restart: unless-stopped
    networks:
      - hanzo-network-platform

  minio:
    image: "minio/minio"
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - files:/data
    restart: unless-stopped
    networks:
      - hanzo-network-platform

  elastic:
    image: "elasticsearch:7.14.2"
    command: |
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - BITNAMI_DEBUG=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8182
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    restart: unless-stopped
    networks:
      - hanzo-network-platform

  rekoni:
    image: hanzoai/rekoni-service:5.1.1
    environment:
      - SECRET=aa2358fe04da55b8e33accc60568634f53eb1bc7f6fb69fca6cb86eb924824e2
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped
    networks:
      - hanzo-network-platform

  transactor:
    image: hanzoai/transactor:5.1.1
    environment:
      - SERVER_PORT=3333
      - SERVER_SECRET=aa2358fe04da55b8e33accc60568634f53eb1bc7f6fb69fca6cb86eb924824e2
      - SERVER_CURSOR_MAXTIMEMS=30000
      - DB_URL=mongodb://mongodb:27017
      - MONGO_URL=mongodb://mongodb:27017
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - FRONT_URL=http://front:8080
      - ACCOUNTS_URL=http://account:3000
      - FULLTEXT_URL=http://fulltext:4700
      - STATS_URL=http://stats:4900
      - LAST_NAME_FIRST=true
    restart: unless-stopped
    networks:
      - hanzo-network-platform

  collaborator:
    image: hanzoai/collaborator:5.1.1
    environment:
      - COLLABORATOR_PORT=3078
      - SECRET=aa2358fe04da55b8e33accc60568634f53eb1bc7f6fb69fca6cb86eb924824e2
      - ACCOUNTS_URL=http://account:3000
      - DB_URL=mongodb://mongodb:27017
      - STATS_URL=http://stats:4900
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
    restart: unless-stopped
    networks:
      - hanzo-network-platform

  account:
    image: hanzoai/account:5.1.1
    environment:
      - SERVER_PORT=3000
      - SERVER_SECRET=aa2358fe04da55b8e33accc60568634f53eb1bc7f6fb69fca6cb86eb924824e2
      - DB_URL=mongodb://mongodb:27017
      - MONGO_URL=mongodb://mongodb:27017
      - TRANSACTOR_URL=ws://transactor:3333;ws://nginx:80/_transactor
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - FRONT_URL=http://front:8080
      - STATS_URL=http://stats:4900
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://account:3000
      - ACCOUNT_PORT=3000
    restart: unless-stopped
    networks:
      - hanzo-network-platform

  workspace:
    image: hanzoai/workspace:5.1.1
    environment:
      - SERVER_SECRET=aa2358fe04da55b8e33accc60568634f53eb1bc7f6fb69fca6cb86eb924824e2
      - DB_URL=mongodb://mongodb:27017
      - MONGO_URL=mongodb://mongodb:27017
      - TRANSACTOR_URL=ws://transactor:3333;ws://nginx:80/_transactor
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
    restart: unless-stopped
    networks:
      - hanzo-network-platform

  front:
    image: hanzoai/front:5.1.1
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_SECRET=aa2358fe04da55b8e33accc60568634f53eb1bc7f6fb69fca6cb86eb924824e2
      - LOVE_ENDPOINT=http://nginx:80/_love
      - ACCOUNTS_URL=http://nginx:80/_accounts
      - REKONI_URL=http://nginx:80/_rekoni
      - CALENDAR_URL=http://nginx:80/_calendar
      - GMAIL_URL=http://nginx:80/_gmail
      - TELEGRAM_URL=http://nginx:80/_telegram
      - STATS_URL=http://nginx:80/_stats
      - UPLOAD_URL=/files
      - ELASTIC_URL=http://elastic:9200
      - COLLABORATOR_URL=ws://nginx:80/_collaborator
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - DB_URL=mongodb://mongodb:27017
      - MONGO_URL=mongodb://mongodb:27017
      - TITLE=Huly Self Host
      - DEFAULT_LANGUAGE=en
      - LAST_NAME_FIRST=true
      - DESKTOP_UPDATES_CHANNEL=selfhost
    restart: unless-stopped
    networks:
      - hanzo-network-platform

  fulltext:
    image: hanzoai/fulltext:5.1.1
    environment:
      - SERVER_SECRET=aa2358fe04da55b8e33accc60568634f53eb1bc7f6fb69fca6cb86eb924824e2
      - DB_URL=mongodb://mongodb:27017
      - FULLTEXT_DB_URL=http://elastic:9200
      - ELASTIC_INDEX_NAME=huly_storage_index
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - REKONI_URL=http://rekoni:4004
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
    restart: unless-stopped
    networks:
      - hanzo-network-platform

  stats:
    image: hanzoai/stats:5.1.1
    environment:
      - PORT=4900
      - SERVER_SECRET=aa2358fe04da55b8e33accc60568634f53eb1bc7f6fb69fca6cb86eb924824e2
    restart: unless-stopped
    networks:
      - hanzo-network-platform

volumes:
  db:
  elastic:
  files:

networks:
  hanzo-network-platform:
    name: hanzo-network-platform
