apiVersion: v1
kind: ConfigMap
metadata:
  name: team-branding
  namespace: team
data:
  branding.json: |
    {
      "hanzo.team": {
        "title": "Hanzo Team",
        "languages": "en,ru,pt,es,zh,fr,de,ja",
        "defaultLanguage": "en",
        "defaultApplication": "tracker",
        "defaultSpace": "tracker:project:DefaultProject",
        "lastNameFirst": "false",
        "defaultSpecial": "issues",
        "links": [
          {
            "rel": "manifest",
            "href": "/hanzoai/site.webmanifest"
          },
          {
            "rel": "icon",
            "href": "/hanzoai/favicon.svg",
            "type": "image/svg+xml"
          },
          {
            "rel": "shortcut icon",
            "href": "/hanzoai/favicon.ico",
            "sizes": "any"
          },
          {
            "rel": "apple-touch-icon",
            "href": "/hanzoai/apple-touch-icon.png"
          }
        ]
      }
    }
