apiVersion: v1
kind: Secret
metadata:
  name: team-secret
  namespace: team
type: Opaque
stringData:
  server-secret: "41522123d407a018fd2ac2b98b8ccf914e6ea8c4b730a35853db23974675e6e8"
  minio-access-key: "hanzo"
  minio-secret-key: "hanzo-minio-secret"
  mongodb-url: "mongodb://root:hanzo-admin-70f08b606241804c@mongodb:27017"
  openid-client-id: "hanzo-team-client-id"
  openid-client-secret: "a7b8c9d0e1f2a3b4c5d6e7f8091a2b3c4d5e6f7a8b9c0d1"
