x-common-env: &common-env
  SERVER_SECRET: sjdhflkusjgfojwehvfjosgfouygwesfojygesouyf
  SECRET: sjdhflkusjgfojwehvfjosgfouygwesfojygesouyf
  STORAGE_CONFIG: minio|minio?accessKey=minioadmin&secretKey=minioadmin
  MONGO_URL: mongodb://mongodb:27017
  DB_URL: mongodb://mongodb:27017
  ACCOUNTS_URL: http://account:3000
  STATS_URL: http://stats:4900

services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - db:/data/db
    networks:
      - internal-services
      - hanzo-network

  minio:
    image: minio/minio
    restart: unless-stopped
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - files:/data
    networks:
      - internal-services
      - hanzo-network

  elastic:
    image: elasticsearch:7.14.2
    restart: unless-stopped
    command: |
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - BITNAMI_DEBUG=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8082
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    networks:
      - internal-services
      - hanzo-network

  rekoni:
    image: hanzoai/rekoni-service:latest
    platform: linux/arm64
    restart: unless-stopped
    environment:
      <<: *common-env
    deploy:
      resources:
        limits:
          memory: 500M
    networks:
      - internal-services
      - hanzo-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rekoni.entrypoints=websecure"
      - "traefik.http.services.rekoni.loadbalancer.server.port=4004"
      - "traefik.http.routers.rekoni.rule=Host(`localhost`) && PathPrefix(`/rekoni`)"
      - "traefik.http.routers.rekoni.middlewares=rekoni-stripprefix"
      - "traefik.http.middlewares.rekoni-stripprefix.stripprefix.prefixes=/rekoni"
      - "traefik.http.routers.rekoni.tls=true"
      - "traefik.http.routers.rekoni.tls.certresolver=myresolver"

  transactor:
    image: hanzoai/transactor:latest
    platform: linux/arm64
    restart: unless-stopped
    environment:
      <<: *common-env
      SERVER_PORT: 3333
      SERVER_CURSOR_MAXTIMEMS: 30000
      FRONT_URL: http://localhost:8087
      FULLTEXT_URL: http://fulltext:4700
      LAST_NAME_FIRST: true
    networks:
      - internal-services
      - hanzo-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transactor-ws.entrypoints=websecure"
      - "traefik.http.routers.transactor-ws.rule=Host(`localhost`) && PathPrefix(`/ws/transactor`)"
      - "traefik.http.routers.transactor-ws.tls=true"
      - "traefik.http.routers.transactor-ws.tls.certresolver=myresolver"
      - "traefik.http.services.transactor-ws.loadbalancer.server.port=3333"
      - "traefik.http.routers.transactor-ws.service=transactor-ws"

      # Strip WebSocket prefix
      - "traefik.http.routers.transactor-ws.middlewares=strip-transactor-ws-prefix"
      - "traefik.http.middlewares.strip-transactor-ws-prefix.stripprefix.prefixes=/ws/transactor"

      # HTTP route for non-WebSocket traffic
      - "traefik.http.routers.transactor.entrypoints=websecure"
      - "traefik.http.routers.transactor.rule=Host(`localhost`) && PathPrefix(`/transactor`)"
      - "traefik.http.routers.transactor.tls=true"
      - "traefik.http.routers.transactor.tls.certresolver=myresolver"
      - "traefik.http.services.transactor.loadbalancer.server.port=3333"
      - "traefik.http.routers.transactor.service=transactor"
      # Strip HTTP prefix
      - "traefik.http.routers.transactor.middlewares=strip-transactor-prefix"
      - "traefik.http.middlewares.strip-transactor-prefix.stripprefix.prefixes=/transactor"

  collaborator:
    image: hanzoai/collaborator:latest
    restart: unless-stopped
    platform: linux/arm64
    environment:
      <<: *common-env
      COLLABORATOR_PORT: 3078
    networks:
      - internal-services
      - hanzo-network
    labels:
      - "traefik.enable=true"
      # WebSocket route
      - "traefik.http.routers.collaborator-ws.entrypoints=websecure"
      - "traefik.http.routers.collaborator-ws.rule=Host(`localhost`) && PathPrefix(`/ws/collaborator`)"
      - "traefik.http.routers.collaborator-ws.tls=true"
      - "traefik.http.routers.collaborator-ws.tls.certresolver=myresolver"
      - "traefik.http.services.collaborator-ws.loadbalancer.server.port=3078"
      - "traefik.http.routers.collaborator-ws.service=collaborator-ws"

      # Strip WebSocket prefix
      - "traefik.http.routers.collaborator-ws.middlewares=strip-collaborator-ws-prefix"
      - "traefik.http.middlewares.strip-collaborator-ws-prefix.stripprefix.prefixes=/ws/collaborator"
      # HTTP route for non-WebSocket traffic
      - "traefik.http.routers.collaborator.entrypoints=websecure"
      - "traefik.http.routers.collaborator.rule=Host(`localhost`) && PathPrefix(`/collaborator`)"
      - "traefik.http.routers.collaborator.tls=true"
      - "traefik.http.routers.collaborator.tls.certresolver=myresolver"
      - "traefik.http.services.collaborator.loadbalancer.server.port=3078"

      # Strip HTTP prefix
      - "traefik.http.routers.collaborator.middlewares=strip-collaborator-prefix"
      - "traefik.http.middlewares.strip-collaborator-prefix.stripprefix.prefixes=/collaborator"

  account:
    image: hanzoai/account:latest
    platform: linux/arm64
    restart: unless-stopped
    environment:
      <<: *common-env
      SERVER_PORT: 3000
      TRANSACTOR_URL: ws://transactor:3333;wss://localhost/ws/transactor
      FRONT_URL: http://front:8080
      MODEL_ENABLED: "*"
      ACCOUNT_PORT: 3000
    networks:
      - internal-services
      - hanzo-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.account.entrypoints=websecure"
      - "traefik.http.services.account.loadbalancer.server.port=3000"
      - "traefik.http.routers.account.rule=Host(`localhost`) && PathPrefix(`/accounts`)"
      - "traefik.http.routers.account.middlewares=account-stripprefix"
      - "traefik.http.middlewares.account-stripprefix.stripprefix.prefixes=/accounts"
      - "traefik.http.routers.account.tls=true"
      - "traefik.http.routers.account.tls.certresolver=myresolver"

  workspace:
    image: hanzoai/workspace:latest
    platform: linux/arm64
    restart: unless-stopped
    environment:
      <<: *common-env
      TRANSACTOR_URL: ws://transactor:3333;wss://localhost/ws/transactor
      MODEL_ENABLED: "*"
    networks:
      - internal-services

  front:
    image: hanzoai/front:latest
    restart: unless-stopped
    platform: linux/arm64
    environment:
      <<: *common-env
      SERVER_PORT: 8080
      ACCOUNTS_URL: https://localhost/accounts
      REKONI_URL: https://localhost/rekoni
      CALENDAR_URL: https://localhost:8095
      GMAIL_URL: https://localhost:8088
      TELEGRAM_URL: https://localhost:8086
      STATS_URL: https://localhost/stats
      UPLOAD_URL: /files
      ELASTIC_URL: http://elastic:9200
      COLLABORATOR_URL: wss://localhost/ws/collaborator
      TITLE: Hanzo Ai Seft Host
      DEFAULT_LANGUAGE: en
      LAST_NAME_FIRST: true
      DESKTOP_UPDATES_CHANNEL: selfhost
    networks:
      - internal-services
      - hanzo-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.services.front.loadbalancer.server.port=8080"
      - "traefik.http.routers.front.rule=Host(`localhost`)"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.tls.certresolver=myresolver"

  fulltext:
    image: hanzoai/fulltext:latest
    restart: unless-stopped
    platform: linux/arm64
    environment:
      <<: *common-env
      FULLTEXT_DB_URL: http://elastic:9200
      ELASTIC_INDEX_NAME: HANZO_storage_index
      REKONI_URL: http://rekoni:4004
    networks:
      - internal-services
      - hanzo-network

  stats:
    image: hanzoai/stats:latest
    restart: unless-stopped
    platform: linux/arm64
    environment:
      <<: *common-env
      PORT: 4900
    networks:
      - internal-services
      - hanzo-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stats.entrypoints=websecure"
      - "traefik.http.services.stats.loadbalancer.server.port=4900"
      - "traefik.http.routers.stats.rule=Host(`localhost`) && PathPrefix(`/stats`)"
      - "traefik.http.routers.stats.middlewares=stats-stripprefix"
      - "traefik.http.middlewares.stats-stripprefix.stripprefix.prefixes=/stats"
      - "traefik.http.routers.stats.tls=true"
      - "traefik.http.routers.stats.tls.certresolver=myresolver"

networks:
  internal-services:
    name: internal-services
  hanzo-network:
    # external: true

volumes:
  db:
  elastic:
  files:
